# Generated by Django 4.0.4 on 2022-05-11 12:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('vgdb', '0003_genre_mode_platform_screenshot_game_genre_game_mode_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='game',
            name='genre',
            field=models.ManyToManyField(blank=True, to='vgdb.genre'),
        ),
        migrations.AlterField(
            model_name='game',
            name='mode',
            field=models.ManyToManyField(blank=True, to='vgdb.mode'),
        ),
        migrations.AlterField(
            model_name='game',
            name='platforms',
            field=models.ManyToManyField(blank=True, to='vgdb.platform'),
        ),
        migrations.AlterField(
            model_name='game',
            name='screenshot',
            field=models.ManyToManyField(blank=True, to='vgdb.screenshot'),
        ),
        migrations.CreateModel(
            name='Fav',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='vgdb.game')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
